const diTokens = {
  STUDENT_REG_CONTROLLER: "STUDENT_REG_CONTROLLER",
  AUTH_CONTROLLER_TOKEN: "AUTH_CONTROLLER_TOKEN",
  STUDENT_REG_DAO: "STUDENT_REG_DAO",
  STUDENT_REG_BO: "STUDENT_REG_BO",
  USERS_DAO: "USERS_DAO",
  USERS_BO: "USERS_BO",
};
export default diTokens;
